/* eslint-disable */
export default {
  "key": "settings",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Settings",
        "export": "Export",
        "import": "Import",
        "reset": "Reset",
        "apiSource": "API Source Selection",
        "sourceSpeedTest": "Source Speed Test",
        "startSpeedTest": "Start Test",
        "testing": "Testing...",
        "optimize": "Optimize",
        "optimizing": "Optimizing...",
        "speedTestHint": "Click 'Start Test' to check speed and latency of all selected sources",
        "appearance": "Appearance",
        "tvNavMode": "TV Navigation Mode",
        "tvNavModeHint": "Use arrow keys to navigate the interface",
        "contentFilter": "Content Filter",
        "yellowFilter": "Adult Content Filter",
        "yellowFilterHint": "Filter adult content in search results",
        "commentaryFilter": "Commentary Filter",
        "commentaryFilterHint": "Auto-filter commentary and movie review videos",
        "adFilter": "Ad Filter",
        "adFilterHint": "Filter ad segments during video playback",
        "playback": "Playback Settings",
        "autoplay": "Autoplay",
        "autoplayHint": "Start playback automatically after page loads",
        "autoplayNext": "Auto Play Next Episode",
        "autoplayNextHint": "Automatically play the next episode after current ends",
        "preloader": "Preloader Settings",
        "cacheSize": "Cache Size",
        "cacheSizeHint": "Maximum video preloader cache size",
        "workerCount": "Concurrent Downloads",
        "workerCountHint": "Number of concurrent download segments for preloading",
        "cacheManagement": "Cache Management",
        "cacheStats": "Cache Statistics",
        "hits": "Hits",
        "misses": "Misses",
        "hitRate": "Hit Rate",
        "total": "Total",
        "memory": "Memory",
        "disk": "Disk",
        "imageCache": "Image Cache",
        "speedCache": "Speed Cache",
        "speedCacheHint": "Cached source speed test results by network environment",
        "clearCache": "Clear Cache",
        "loading": "Loading...",
        "cacheCleared": "Cache cleared",
        "clearCacheFailed": "Failed to clear cache",
        "speedCacheCleared": "Speed cache cleared",
        "speedCacheClearFailed": "Failed to clear speed cache",
        "speedTestComplete": "Speed test complete",
        "speedTestFailed": "Speed test failed",
        "optimizeSuccess": "Optimized: kept {kept} available sources, removed {removed} invalid sources",
        "allSourcesAvailable": "All {count} sources are available",
        "optimizeFailed": "Optimization failed",
        "configExported": "Configuration exported",
        "configImportSuccess": "Configuration imported successfully",
        "configImportFailed": "Configuration import failed, please check the file format",
        "selectSourceWarning": "Please select at least one API source first",
        "theme": "Theme",
        "light": "Light",
        "dark": "Dark",
        "system": "System",
        "gridDensity": "Grid Density",
        "compact": "Compact",
        "standard": "Standard",
        "loose": "Loose",
        "apiSelectorHint": "Select video sources to use, at least one required",
        "selectAll": "Select All",
        "reverseSelect": "Reverse",
        "customApi": "Custom API Sources",
        "addedCount": "{n} added",
        "name": "Name",
        "apiUrl": "API URL",
        "add": "Add",
        "selectSource": "Select Source",
        "noSourcesAvailable": "No sources available",
        "loadingSources": "Loading sources...",
        "playNow": "Play Now",
        "addToFavourites": "Add to Favourites",
        "removeFromFavourites": "Remove from Favourites",
        "addedToFavourites": "Added to favourites",
        "removedFromFavourites": "Removed from favourites",
        "language": "Language",
        "english": "English",
        "chinese": "简体中文"
      },
      "zh-Hans": {
        "title": "设置",
        "export": "导出",
        "import": "导入",
        "reset": "重置",
        "apiSource": "API 源选择",
        "sourceSpeedTest": "源测速",
        "startSpeedTest": "开始测速",
        "testing": "测速中...",
        "optimize": "优化源",
        "optimizing": "优化中...",
        "speedTestHint": "点击'开始测速'检测所有已选源的速度和延迟",
        "appearance": "外观",
        "tvNavMode": "TV 导航模式",
        "tvNavModeHint": "使用方向键在界面中导航",
        "contentFilter": "内容过滤",
        "yellowFilter": "黄色内容过滤",
        "yellowFilterHint": "搜索结果中过滤成人内容",
        "commentaryFilter": "解说过滤",
        "commentaryFilterHint": "自动过滤解说、电影解说等视频",
        "adFilter": "广告过滤",
        "adFilterHint": "过滤视频播放中的广告片段",
        "playback": "播放设置",
        "autoplay": "自动播放",
        "autoplayHint": "页面加载后自动开始播放",
        "autoplayNext": "自动连播",
        "autoplayNextHint": "播放完毕后自动播放下一集",
        "preloader": "预加载设置",
        "cacheSize": "缓存大小",
        "cacheSizeHint": "视频预加载缓存最大占用",
        "workerCount": "并发下载数",
        "workerCountHint": "预加载时并发下载的分段数",
        "cacheManagement": "缓存管理",
        "cacheStats": "缓存统计",
        "hits": "命中",
        "misses": "未命中",
        "hitRate": "命中率",
        "total": "总计",
        "memory": "内存",
        "disk": "磁盘",
        "imageCache": "图片缓存",
        "speedCache": "速度缓存",
        "speedCacheHint": "按网络环境保存的源测速结果",
        "clearCache": "清除缓存",
        "loading": "加载中...",
        "cacheCleared": "缓存已清除",
        "clearCacheFailed": "清除缓存失败",
        "speedCacheCleared": "速度缓存已清除",
        "speedCacheClearFailed": "清除速度缓存失败",
        "speedTestComplete": "测速完成",
        "speedTestFailed": "测速失败",
        "optimizeSuccess": "已优化：保留 {kept} 个可用源，移除 {removed} 个无效源",
        "allSourcesAvailable": "所有 {count} 个源均可正常使用",
        "optimizeFailed": "优化失败",
        "configExported": "配置导出成功",
        "configImportSuccess": "配置导入成功",
        "configImportFailed": "配置导入失败，请检查文件格式",
        "selectSourceWarning": "请先选择至少一个 API 源",
        "theme": "主题",
        "light": "浅色",
        "dark": "深色",
        "system": "跟随系统",
        "gridDensity": "每行显示数量",
        "compact": "紧凑",
        "standard": "标准",
        "loose": "宽松",
        "apiSelectorHint": "选择要使用的视频源，至少选择一个",
        "selectAll": "全选",
        "reverseSelect": "反选",
        "customApi": "自定义 API 源",
        "addedCount": "已添加 {n} 个",
        "name": "名称",
        "apiUrl": "API 地址",
        "add": "添加",
        "selectSource": "选择播放源",
        "noSourcesAvailable": "暂无可用播放源",
        "loadingSources": "加载播放源中...",
        "playNow": "立即播放",
        "addToFavourites": "添加到收藏",
        "removeFromFavourites": "取消收藏",
        "addedToFavourites": "已添加到收藏",
        "removedFromFavourites": "已取消收藏",
        "language": "语言",
        "english": "English",
        "chinese": "简体中文"
      }
    }
  },
  "localIds": [
    "settings::local::src/lib/intlayer/content/settings.content.ts"
  ]
} as const;
